== Plugin configuration

Après téléchargement du plugin, il vous faudra simplement activer le plugin

== Equipment configuration

La configuration des équipements Denon est accessible à partir du menu Plugins puis multimedia

Vous retrouvez ici toute la configuration de votre équipement : 

* *Nom de l'équipement Denon* : nom de votre équipement Denon,
* *Objet parent* : indique l'objet parent auquel appartient l'équipement,
* *Catégorie* : les catégories de l'équipement (il peut appartenir à plusieurs catégories),
* *Activer* : permet de rendre votre équipement actif,
* *Visible* : rend votre équipement visible sur le dashboard,
* *IP* : IP de l'amplificateur denon
* *Zone* : zone à contrôler (principale ou zone 2)

En dessous vous retrouvez la liste des commandes : 

* *Nom* : le nom affiché sur le dashboard,
* *Configuration avancé* : permet d'afficher la fenêtre de configuration avancée de la commande,
* *Options* : vous permet d'afficher ou de masquer certaines commandes et/ou d'en historiser
* *Tester* : permet de tester la commande

[NOTE]
Les commandes sont générées automatiquement en fonction du modèle de votre amplificateur